'use strict';

// A03:2021 — Injection
// Covers: JavaScript/TypeScript, PHP, Python, Java, Go, Ruby, C#, Bash/Shell

const RULES = [
  // ── SQL Injection — JavaScript/TypeScript ─────────────────────
  {
    id: 'INJ-001',
    name: 'SQL Injection — String Concatenation (JS)',
    severity: 'HIGH',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['javascript', 'typescript'],
    pattern: /(?:query|execute|exec|raw)\s*\(\s*['"`][^'"`)]*(?:SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE)[^'"`)]*['"`]\s*\+/gi,
    description: 'SQL query built by string concatenation. Attackers can inject SQL operators to bypass authentication, dump data, or destroy tables.',
    remediation: 'Use parameterized queries: db.query("SELECT * FROM users WHERE id = ?", [id]). Never build SQL strings with + or template literals.',
  },
  {
    id: 'INJ-002',
    name: 'SQL Injection — Template Literal (JS)',
    severity: 'HIGH',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['javascript', 'typescript'],
    pattern: /(?:query|execute|exec|raw)\s*\(\s*`[^`]*(?:SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE)[^`]*\$\{/gi,
    description: 'SQL query built with template literal variable interpolation. Equivalent to concatenation — fully injectable.',
    remediation: 'Use query placeholders: knex.raw("SELECT * FROM users WHERE id = ?", [id]) or ORM query builders.',
  },
  {
    id: 'INJ-003',
    name: 'Code Injection — eval() With User Input (JS)',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-95',
    tech: ['javascript', 'typescript'],
    pattern: /\beval\s*\([^)]*(?:req\.|request\.|params\.|body\.|query\.|input|data|user)/gi,
    description: 'eval() with user-controlled input enables arbitrary code execution on the server (RCE). Full system compromise is possible.',
    remediation: 'Never use eval() with user input. Use JSON.parse() for JSON, or redesign the logic without dynamic code execution.',
  },
  {
    id: 'INJ-004',
    name: 'Command Injection — Shell Execution (JS)',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    tech: ['javascript', 'typescript'],
    pattern: /(?:child_process\.)?(?:exec|execSync|spawn|spawnSync|execFile|execFileSync)\s*\(\s*(?:[^,)]*\+[^,)]*|`[^`]*\$\{)/gi,
    description: 'Shell command constructed with dynamic values. Attackers can inject shell metacharacters: ; rm -rf / or | cat /etc/passwd',
    remediation: 'Use execFile() with separate argument arrays instead of exec(). Validate inputs against strict allowlists. Use shell: false in spawn().',
  },
  {
    id: 'INJ-005',
    name: 'NoSQL Injection — Unvalidated Query (JS)',
    severity: 'HIGH',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-943',
    tech: ['javascript', 'typescript'],
    pattern: /\.(?:find|findOne|findById|updateOne|updateMany|deleteOne|deleteMany|aggregate)\s*\(\s*(?:req\.|request\.)\w+/gi,
    description: 'MongoDB query using raw request data. Attackers can inject { "$gt": "" } operators to bypass authentication or dump all records.',
    remediation: 'Validate and sanitize query parameters using Joi or express-validator. Cast types explicitly: { _id: mongoose.Types.ObjectId(req.params.id) }',
  },
  {
    id: 'INJ-006',
    name: 'XPath Injection (JS)',
    severity: 'HIGH',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-643',
    tech: ['javascript', 'typescript'],
    pattern: /xpath.*(?:\+|`[^`]*\$\{).*(?:req\.|input|user|param)/gi,
    description: 'XPath query built with user input enables XPath injection — can bypass authentication or extract XML data.',
    remediation: 'Use parameterized XPath (XPathExpression with variables). Escape all special chars before XPath evaluation.',
  },
  {
    id: 'INJ-007',
    name: 'LDAP Injection (JS)',
    severity: 'HIGH',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-90',
    tech: ['javascript', 'typescript'],
    pattern: /ldap(?:Search|Query|Bind|Filter)\s*\([^)]*(?:\+|`[^`]*\$\{)[^)]*(?:req\.|input|user|param)/gi,
    description: 'LDAP filter built with user input. Attackers inject LDAP metacharacters (*)(uid=*))(|(uid=* to bypass authentication.',
    remediation: 'Escape LDAP special characters: & | ! = < > ~ * ( ) \\ /. Use the ldapjs filter builder.',
  },

  // ── PHP ──────────────────────────────────────────────────────
  {
    id: 'INJ-010',
    name: 'SQL Injection — mysql_query() PHP (Deprecated)',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['php'],
    pattern: /mysql_query\s*\(\s*["'`][^"'`]*(?:SELECT|INSERT|UPDATE|DELETE)[^"'`]*["'`]\s*\.\s*\$_(?:GET|POST|REQUEST|COOKIE)/gi,
    description: 'mysql_query() with user input concatenated directly. The old mysql_ extension has no parameterized query support and is removed in PHP 7+.',
    remediation: 'Migrate to PDO or MySQLi with prepared statements: $stmt = $pdo->prepare("SELECT * FROM users WHERE id = ?"); $stmt->execute([$id]);',
  },
  {
    id: 'INJ-011',
    name: 'SQL Injection — mysqli_query() PHP',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['php'],
    pattern: /mysqli_query\s*\(\s*\$\w+\s*,\s*["'`][^"'`]*(?:SELECT|INSERT|UPDATE|DELETE)[^"'`]*\.\s*\$_(?:GET|POST|REQUEST)/gi,
    description: 'mysqli_query() with unsanitized user input. Concatenating $_GET/$_POST directly into SQL is classic SQL injection.',
    remediation: 'Use prepared statements: $stmt = $mysqli->prepare("SELECT * FROM users WHERE email = ?"); $stmt->bind_param("s", $email); $stmt->execute();',
  },
  {
    id: 'INJ-012',
    name: 'Command Injection — system()/exec() PHP',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    tech: ['php'],
    pattern: /(?:system|exec|shell_exec|passthru|popen|proc_open)\s*\(\s*(?:[^,)]*\.\s*\$_(?:GET|POST|REQUEST)|`[^`]*\$_(?:GET|POST))/gi,
    description: 'PHP system/exec/shell_exec with user input. Attackers append ; whoami or | cat /etc/passwd to execute arbitrary commands.',
    remediation: 'Use escapeshellarg() for each argument. Prefer PHP native functions over shell commands. Use strict input validation.',
  },
  {
    id: 'INJ-013',
    name: 'Code Injection — eval() PHP',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-95',
    tech: ['php'],
    pattern: /\beval\s*\(\s*(?:[^)]*\$_(?:GET|POST|REQUEST|COOKIE)|base64_decode\s*\(\s*\$_)/gi,
    description: 'PHP eval() with user-controlled or base64-decoded input. Attackers can execute arbitrary PHP code and achieve full server compromise.',
    remediation: 'Remove all eval() calls. eval() has no legitimate use with user input. Redesign the logic.',
  },
  {
    id: 'INJ-014',
    name: 'File Inclusion Injection — include/require PHP',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-98',
    tech: ['php'],
    pattern: /(?:include|require|include_once|require_once)\s*\(\s*\$_(?:GET|POST|REQUEST|COOKIE)/gi,
    description: 'PHP file inclusion with user-controlled path. Attackers can include local files (/etc/passwd) or remote files (if allow_url_include=On) for RCE.',
    remediation: 'Never use user input in include/require. Use a whitelist of allowed template names: $allowed = ["header","footer"]; include("templates/" . $allowed[$key] . ".php");',
  },

  // ── Python ───────────────────────────────────────────────────
  {
    id: 'INJ-020',
    name: 'SQL Injection — cursor.execute() Python',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['python'],
    pattern: /cursor\.execute\s*\(\s*(?:f['"`]|['"`][^'"`)]*(?:SELECT|INSERT|UPDATE|DELETE)[^'"`)]*['"`]\s*%|["'`][^"'`]*(?:SELECT|INSERT|UPDATE|DELETE)[^"'`]*\+\s*\w)/gi,
    description: 'Python database cursor.execute() with string formatting or concatenation. %-formatting and f-strings in SQL are directly injectable.',
    remediation: 'Always use parameter substitution: cursor.execute("SELECT * FROM users WHERE id = %s", (user_id,)) — note the trailing comma for the tuple.',
  },
  {
    id: 'INJ-021',
    name: 'Command Injection — os.system() / subprocess Python',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    tech: ['python'],
    pattern: /(?:os\.system|subprocess\.(?:call|run|Popen|check_output|check_call))\s*\(\s*(?:f['"`]|['"`][^'"`)]*\+|\w+\s*\+)/gi,
    description: 'Python os.system() or subprocess with shell=True and string-built command. Attackers inject shell metacharacters.',
    remediation: 'Use subprocess.run() with a list of arguments and shell=False: subprocess.run(["ls", "-la", path], shell=False). Validate path with os.path.realpath().',
  },
  {
    id: 'INJ-022',
    name: 'SQL Injection — SQLAlchemy raw() Python',
    severity: 'HIGH',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['python'],
    pattern: /(?:db\.session\.execute|engine\.execute|connection\.execute)\s*\(\s*(?:f['"`]|text\s*\(\s*f['"`])/gi,
    description: 'SQLAlchemy execute() with f-string query. SQLAlchemy\'s text() with f-strings bypasses parameter escaping.',
    remediation: 'Use SQLAlchemy text() with bindparams: db.execute(text("SELECT * FROM users WHERE id = :id"), {"id": user_id})',
  },
  {
    id: 'INJ-023',
    name: 'LDAP Injection — Python ldap3',
    severity: 'HIGH',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-90',
    tech: ['python'],
    pattern: /conn\.search\s*\([^)]*(?:f['"`]|['"`][^'"`)]*\+\s*\w)/gi,
    description: 'Python ldap3 conn.search() with unsanitized user input. LDAP injection can bypass authentication.',
    remediation: 'Escape LDAP special chars using ldap3.utils.conv.escape_filter_chars(). Use attribute-value pairs in filter construction.',
  },

  // ── Java ─────────────────────────────────────────────────────
  {
    id: 'INJ-030',
    name: 'SQL Injection — Statement.execute() Java',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['java'],
    pattern: /Statement\s*\.\s*(?:execute|executeQuery|executeUpdate)\s*\(\s*['"`][^'"`)]*(?:SELECT|INSERT|UPDATE|DELETE)[^'"`)]*['"`]\s*\+/gi,
    description: 'Java Statement.execute() with concatenated SQL. PreparedStatement should always be used for parameterized queries.',
    remediation: 'Use PreparedStatement: PreparedStatement stmt = conn.prepareStatement("SELECT * FROM users WHERE id = ?"); stmt.setInt(1, userId); ResultSet rs = stmt.executeQuery();',
  },
  {
    id: 'INJ-031',
    name: 'SQL Injection — createQuery() JPA/Hibernate Java',
    severity: 'HIGH',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['java'],
    pattern: /createQuery\s*\(\s*['"`][^'"`)]*(?:FROM|WHERE)[^'"`)]*['"`]\s*\+/gi,
    description: 'JPA/Hibernate createQuery() with string concatenation creates injectable HQL/JPQL queries.',
    remediation: 'Use named parameters: em.createQuery("FROM User u WHERE u.email = :email").setParameter("email", email)',
  },
  {
    id: 'INJ-032',
    name: 'Command Injection — Runtime.exec() Java',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    tech: ['java'],
    pattern: /Runtime\.getRuntime\s*\(\s*\)\s*\.\s*exec\s*\(\s*(?:[^)]*\+|new\s+String\[\])/gi,
    description: 'Java Runtime.exec() with dynamic command string or array built from user input enables OS command injection.',
    remediation: 'Use ProcessBuilder with a string array: new ProcessBuilder("ls", "-la", sanitizedPath). Validate all inputs against strict allowlists.',
  },

  // ── Go ───────────────────────────────────────────────────────
  {
    id: 'INJ-040',
    name: 'SQL Injection — db.Query() with fmt.Sprintf (Go)',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['go'],
    pattern: /db\.(?:Query|Exec|QueryRow)\s*\(\s*fmt\.Sprintf\s*\(\s*['"`][^'"`)]*(?:SELECT|INSERT|UPDATE|DELETE)/gi,
    description: 'Go database query built with fmt.Sprintf. This is the most common SQL injection pattern in Go code.',
    remediation: 'Use parameterized queries: db.Query("SELECT * FROM users WHERE id = $1", userID). Never use fmt.Sprintf to build SQL.',
  },
  {
    id: 'INJ-041',
    name: 'Command Injection — exec.Command() with user input (Go)',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    tech: ['go'],
    pattern: /exec\.Command\s*\(\s*(?:fmt\.Sprintf|r\.(?:FormValue|URL\.Query)|userInput|\w+Input)/gi,
    description: 'Go exec.Command() with user-controlled arguments enables command injection.',
    remediation: 'Validate all arguments. Never pass user-controlled strings as the command name. Use exec.Command("fixed-binary", validatedArg) with strict input validation.',
  },

  // ── Ruby ─────────────────────────────────────────────────────
  {
    id: 'INJ-050',
    name: 'SQL Injection — ActiveRecord where() with String (Ruby)',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['ruby'],
    pattern: /\.where\s*\(\s*['"`][^'"`)]*(?:=|LIKE|WHERE)[^'"`)]*#\{/gi,
    description: 'ActiveRecord where() with string interpolation. Ruby #{} in SQL strings creates injectable queries despite ActiveRecord protection.',
    remediation: 'Use array or hash conditions: User.where("name = ?", params[:name]) or User.where(name: params[:name]). Never interpolate with #{} in SQL strings.',
  },
  {
    id: 'INJ-051',
    name: 'Command Injection — Backtick/system() Ruby',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    tech: ['ruby'],
    pattern: /(?:`[^`]*#\{(?:params|request\.)\w+|system\s*\(\s*['"`][^'"`)]*#\{(?:params|request\.)|exec\s*\(\s*['"`][^'"`)]*#\{(?:params|request\.))/gi,
    description: 'Ruby backtick command execution or system() with user input. Attackers inject semicolons and shell commands.',
    remediation: 'Use Open3.popen3() with argument arrays: Open3.capture3("ls", "-la", safe_path). Avoid backticks entirely with user data.',
  },

  // ── C# / .NET ─────────────────────────────────────────────────
  {
    id: 'INJ-060',
    name: 'SQL Injection — SqlCommand with Concatenation (C#)',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    tech: ['csharp'],
    pattern: /new\s+SqlCommand\s*\(\s*(?:['"`][^'"`)]*(?:SELECT|INSERT|UPDATE|DELETE)[^'"`)]*['"`]\s*\+|string\.Format\s*\(\s*['"`][^'"`)]*(?:SELECT|INSERT|UPDATE|DELETE))/gi,
    description: 'C# SqlCommand built with string concatenation or string.Format. Classic SQL injection vulnerability.',
    remediation: 'Use SqlCommand with parameters: cmd.Parameters.AddWithValue("@userId", userId). Or use Entity Framework with LINQ queries.',
  },
  {
    id: 'INJ-061',
    name: 'Command Injection — Process.Start() C#',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    tech: ['csharp'],
    pattern: /Process\.Start\s*\(\s*(?:new\s+ProcessStartInfo\s*\()?(?:Request\.(?:Query|Form)|HttpContext\.Request)/gi,
    description: 'C# Process.Start() with user-controlled input enables OS command injection.',
    remediation: 'Validate all inputs. Use ProcessStartInfo with separate FileName and Arguments. Never build command strings from user input.',
  },

  // ── Bash / Shell ──────────────────────────────────────────────
  {
    id: 'INJ-070',
    name: 'Shell Script — Unquoted Variable Expansion',
    severity: 'HIGH',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    tech: ['bash', 'shell'],
    pattern: /\b(?:eval|exec|sh\s+-c)\s+\$(?!\(|\{[^}]+\})\w+/gi,
    description: 'Shell script uses unquoted variable in eval/exec. Attackers controlling the variable can inject additional commands.',
    remediation: 'Quote all variable expansions: eval "$variable". Avoid eval entirely. Use printf or proper argument passing.',
  },
  {
    id: 'INJ-071',
    name: 'Shell Script — Command Injection via Input',
    severity: 'CRITICAL',
    category: 'Injection',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    tech: ['bash', 'shell'],
    pattern: /(?:read\s+\w+[\s\S]{0,200}eval|eval\s+[^(](?!['"`].*['"`]))/gi,
    description: 'Shell script reads user input and passes it to eval — full command injection.',
    remediation: 'Never eval user input in shell scripts. Validate input with regex before any processing.',
  },
];

function detectColumn(line, pattern) {
  const p = new RegExp(pattern.source, pattern.flags.replace('g', ''));
  const match = p.exec(line);
  return match ? match.index + 1 : 1;
}

function scan(code, filePath) {
  const findings = [];
  const lines = code.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    for (const rule of RULES) {
      rule.pattern.lastIndex = 0;
      if (rule.pattern.test(line)) {
        findings.push({
          ruleId: rule.id,
          ruleName: rule.name,
          severity: rule.severity,
          category: rule.category,
          owasp: rule.owasp,
          cwe: rule.cwe || 'CWE-89',
          tech: rule.tech,
          description: rule.description,
          file: filePath,
          line: i + 1,
          column: detectColumn(line, rule.pattern),
          snippet: line.trim().substring(0, 300),
          remediation: rule.remediation,
          source: 'owasp-rules',
        });
      }
    }
  }
  return findings;
}

module.exports = { scan, RULES };
