'use strict';

const PDFDocument = require('pdfkit');

/**
 * Generate a professional PDF security report
 * @param {Object} report - Report data from database
 * @returns {PDFDocument} - PDF stream
 */
function generateReportPDF(report) {
  const doc = new PDFDocument({ 
    size: 'A4', 
    margin: 50,
    info: {
      Title: `Security Report - ${report.projectName}`,
      Author: 'CodeGuardian',
      Subject: `PR #${report.pullRequestId} Security Analysis`,
    }
  });

  // Colors
  const colors = {
    primary: '#5b6af0',
    critical: '#ef4444',
    high: '#f97316',
    medium: '#eab308',
    low: '#22c55e',
    text: '#1a202c',
    textLight: '#718096',
  };

  // Header
  doc.fontSize(24).fillColor(colors.primary).text('Security Scan Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor(colors.textLight).text(new Date().toLocaleString(), { align: 'center' });
  doc.moveDown(2);

  // Project Info
  doc.fontSize(14).fillColor(colors.text).text('Project Information', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10);
  doc.fillColor(colors.textLight).text('Project: ', { continued: true }).fillColor(colors.text).text(report.projectName);
  doc.fillColor(colors.textLight).text('Pull Request: ', { continued: true }).fillColor(colors.text).text(`#${report.pullRequestId} - ${report.pullRequestTitle}`);
  doc.fillColor(colors.textLight).text('Scanned At: ', { continued: true }).fillColor(colors.text).text(new Date(report.scannedAt).toLocaleString());
  doc.fillColor(colors.textLight).text('Files Scanned: ', { continued: true }).fillColor(colors.text).text(report.filesScanned.toString());
  doc.fillColor(colors.textLight).text('Lines Scanned: ', { continued: true }).fillColor(colors.text).text(report.linesScanned.toLocaleString());
  doc.moveDown(2);

  // Risk Summary Box
  doc.fontSize(14).fillColor(colors.text).text('Risk Assessment', { underline: true });
  doc.moveDown(0.5);
  
  const riskColor = getRiskColor(report.riskLevel, colors);
  doc.fontSize(12).fillColor(riskColor).text(`Risk Level: ${report.riskLevel}`, { continued: true });
  doc.fillColor(colors.text).text(`  |  Risk Score: ${report.riskScore}/100`);
  doc.moveDown(1.5);

  // Severity Summary
  doc.fontSize(14).fillColor(colors.text).text('Findings Summary', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10);
  
  const summary = report.summary;
  if (summary.critical > 0) doc.fillColor(colors.critical).text(`Critical: ${summary.critical}`, { continued: true }).fillColor(colors.text).text('  ');
  if (summary.high > 0) doc.fillColor(colors.high).text(`High: ${summary.high}`, { continued: true }).fillColor(colors.text).text('  ');
  if (summary.medium > 0) doc.fillColor(colors.medium).text(`Medium: ${summary.medium}`, { continued: true }).fillColor(colors.text).text('  ');
  if (summary.low > 0) doc.fillColor(colors.low).text(`Low: ${summary.low}`, { continued: true }).fillColor(colors.text).text('  ');
  doc.fillColor(colors.text).text(`Total: ${summary.total}`);
  doc.moveDown(2);

  // Findings Details
  if (report.findings && report.findings.length > 0) {
    doc.addPage();
    doc.fontSize(14).fillColor(colors.text).text('Detailed Findings', { underline: true });
    doc.moveDown(1);

    // Group by severity
    const grouped = groupBySeverity(report.findings);
    
    ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].forEach(severity => {
      const findings = grouped[severity] || [];
      if (findings.length === 0) return;

      doc.fontSize(12).fillColor(getSeverityColor(severity, colors)).text(`${severity} (${findings.length})`, { underline: true });
      doc.moveDown(0.5);

      findings.forEach((finding, idx) => {
        if (doc.y > 700) doc.addPage();

        doc.fontSize(10).fillColor(colors.text).text(`${idx + 1}. ${finding.ruleName}`, { bold: true });
        doc.fontSize(9).fillColor(colors.textLight);
        doc.text(`   Category: ${finding.category} | OWASP: ${finding.owasp}`);
        doc.text(`   File: ${finding.file}:${finding.line}`);
        doc.fillColor(colors.text).text(`   ${finding.description}`);
        
        if (finding.remediation) {
          doc.fillColor(colors.low).text(`   ✓ Fix: ${finding.remediation}`);
        }
        
        doc.moveDown(0.5);
      });

      doc.moveDown(1);
    });
  }

  // Footer on last page
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(8).fillColor(colors.textLight);
    doc.text(
      `Page ${i + 1} of ${range.count} | Generated by CodeGuardian`,
      50,
      doc.page.height - 50,
      { align: 'center' }
    );
  }

  doc.end();
  return doc;
}

function getRiskColor(riskLevel, colors) {
  const map = {
    CRITICAL: colors.critical,
    HIGH: colors.high,
    MEDIUM: colors.medium,
    LOW: colors.low,
    NONE: colors.low,
  };
  return map[riskLevel] || colors.text;
}

function getSeverityColor(severity, colors) {
  const map = {
    CRITICAL: colors.critical,
    HIGH: colors.high,
    MEDIUM: colors.medium,
    LOW: colors.low,
  };
  return map[severity] || colors.text;
}

function groupBySeverity(findings) {
  return findings.reduce((acc, f) => {
    if (!acc[f.severity]) acc[f.severity] = [];
    acc[f.severity].push(f);
    return acc;
  }, {});
}

module.exports = { generateReportPDF };
